version: '3.1'

services:

  app:
    build: .
    container_name: app
    command: gunicorn apigiftbiscuit.wsgi:application --bind 0.0.0.0:8082
    volumes:
      - .:/var/www/html
    ports:
      - '8082:8082'
    env_file:
      - ./.env.dev
    links:
      - db
    depends_on: 
      - db

  db:
    image: mysql:8
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db_giftbiscuit
    ports:
      - 3306:3306

volumes:
  mysql_data: