# Generated by Django 3.0.4 on 2020-05-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0005_auto_20200502_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description_short',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição curta:'),
        ),
    ]
