# Generated by Django 3.0.4 on 2020-05-23 14:09

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20200517_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=froala_editor.fields.FroalaField(verbose_name='Mensagem:'),
        ),
    ]
