# Generated by Django 3.0.4 on 2020-06-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-id'], 'verbose_name': 'Página', 'verbose_name_plural': 'Páginas'},
        ),
    ]
